name: bot-taks-scheduler
on:
    schedule:
        - cron: '0 1 * * *' #01 Hour UTC = 8 Hour GMT+7
        - cron: '0 6 * * *' #06 Hour UTC = 13 Hour GMT+7
        - cron: '0 12 * * *' #06 Hour UTC = 19 Hour GMT+7
    workflow_dispatch:
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: Check Repo
              uses: actions/checkout@v2.3.4
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.1.4
            - name: Set TimeZone for JS environment
              uses: szenius/set-timezone@v1.0
              with:
                  timezoneLinux: 'Asia/Bangkok'
            - name: Install Node.js dependencies
              run: npm install
            - name: Setup Python Environment
              uses: actions/setup-python@v2.2.1
            - name: Install Python dependencies
              working-directory: bot_jobs
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Get Provincial Datasets from the Government
              working-directory: bot_jobs
              run: python get_provincial_dataset.py
            - name: Build Province and District cases
              working-directory: bot_jobs
              run: python build_province_and_district_cases.py
            - name: Get National Data From djay/covidthailand
              working-directory: bot_jobs
              run: node get_data.js
            - name: Get testing dataset
              working-directory: bot_jobs
              run: python get_covid_test_dataset.py
            - name: Get vaccination datasets
              working-directory: bot_jobs/vaccination
              run: |
                  node get-national-data.js
              # node fetch-MOPH-dashboard.js
            - name: Build Province Graphs in svg using Python
              working-directory: bot_jobs
              run: python build_province_graph.py
            - name: Commit Changes to Git Repo
              run: |
                  git config --global user.name "porames"
                  git config --global user.email "porames@users.noreply.github.com"
                  git add -A
                  git commit -m "[Bot ðŸ¤–] build data from today's dataset $(date)"
                  git push
